```{r}
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(survival))
suppressPackageStartupMessages(library(mets))
suppressPackageStartupMessages(library(plyr))
suppressPackageStartupMessages(library(rhdf5))
```

```{r}
reformat_pk_id <- function(x) paste("pk_", as.character(x), sep="")
# function to add pk_ prefix to pk local_Labs
```

```{r}
mtb_dt <- fread(file="ARrLCpos64FrPksOfInterest_plusRelevantPT_for7562samples.csv", header=TRUE)
dim(mtb_dt)
```

```{r}
mtb_list <- sapply(colnames(mtb_dt)[11:(length(colnames(mtb_dt))-2)], function(x) reformat_pk_id(x))
colnames(mtb_dt) <- c('ID_C_x', 'ID', 'age', 'sex', 'sex_01', 'BMI', 'race', 't2d_inc', 't2d_inc_time', 'SampleID', mtb_list, "ID_C_y", "FTRB05")
```

```{r}
basic_covariates = c("age","sex_01","BMI")
event = 't2d_inc'
time = 't2d_inc_time'
outcome = 'T2D'
N_event_thresh = 10
```

```{r}
# cap upper outliers 
cap_upper_outliers_scale <- function(x) {
  iqr = IQR(x, na.rm=T)
  qnt_upper <- quantile(x, probs=c(.75), na.rm=T)
  cap_upper <- quantile(x, probs=c(.999), na.rm=T)
  x[x > (qnt_upper + 4*iqr)] <- cap_upper
  x <- scale(x) # Z-score mtb values
  return(x)
}
```

```{r}
# Cox regression function on event time
cox_regression_func <- function(dt, event, time, covariates, mtb_var) { 
    # function to run Cox regression for single mtb feature
  dt[[mtb_var]] <- cap_upper_outliers_scale(dt[[mtb_var]])
  dt <- dt[complete.cases(dt)] 
    # remove rows with missing values in any column of data frame; 
    # in this case with data subsetted before should not do anything, but just in case
  if (nrow(dt[dt[[event]] == 1]) > N_event_thresh ) { 
    # if enough cases; cases are marked by 1 in pheno_dt event column
    f <- paste(paste("Surv(",time,", ",event,")",sep=""), "~", paste(c(covariates, mtb_var), collapse=" + ")) 
      # make regression formula
    mod = coxph(as.formula(f), data=dt)
    mod_sum = summary(mod)
    
    # make table from coxph() output
    frame <- data.table(
      metabolite = mtb_var,
      pvalue = mod_sum$coefficients[mtb_var,'Pr(>|z|)'],
      hr = mod_sum$coefficients[mtb_var, 'exp(coef)'],
      hr_lowerCI = mod_sum$conf.int[mtb_var, 'lower .95'],
      hr_upperCI = mod_sum$conf.int[mtb_var, 'upper .95'],
      beta = mod_sum$coefficients[mtb_var,'coef'],
      se = mod_sum$coefficients[mtb_var,'se(coef)'],
      z = mod_sum$coefficients[mtb_var,'z'])
    
    # add results for covars
    for (covar in covariates) {
      frame[ , (paste(covar, 'pvalue', sep='_')) := mod_sum$coefficients[covar,'Pr(>|z|)']]
      frame[ , (paste(covar, 'hr', sep='_')) := mod_sum$coefficients[covar,'exp(coef)']]
      frame[ , (paste(covar, 'hr_lowerCI', sep='_')) := mod_sum$conf.int[covar,'lower .95']]
      frame[ , (paste(covar, 'hr_upperCI', sep='_')) := mod_sum$conf.int[covar,'upper .95']]
      frame[ , (paste(covar, 'beta', sep='_')) := mod_sum$coefficients[covar,'coef']]
      frame[ , (paste(covar, 'se', sep='_')) := mod_sum$coefficients[covar,'se(coef)']]
      frame[ , (paste(covar, 'z', sep='_')) := mod_sum$coefficients[covar,'z']]
    }
    frame[ , 'n_total' := mod_sum$n]
    frame[ , 'n_event' := mod_sum$nevent]    
  }
    return(frame)
}
```

```{r}
# run Cox regression
cox_res_dt <- ldply(mtb_list, function(mtb_var)
	      cox_regression_func(mtb_dt, event=event, time=time, covariates=basic_covariates, mtb_var=mtb_var),
	      .parallel = FALSE) 
cox_res_dt$.id <- NULL # remove this column
setorder(cox_res_dt, pvalue)
fwrite(cox_res_dt, 'ARrLCpos64FrPksOfInterest_CoxT2Dinc_Basic_on7562Samples.csv')
```
